--------------------------------------------------------
--  File created - Friday-August-12-2016   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table DES_PROFILE_FASTEL_AM
--------------------------------------------------------

  CREATE TABLE "FASTEL"."DES_PROFILE_FASTEL_AM" 
   (	"NOTEL" VARCHAR2(15 BYTE), 
	"NIP_NAS" NUMBER(8,0) DEFAULT NULL, 
	"STANDARD_NAME" VARCHAR2(150 BYTE) DEFAULT NULL, 
	"ALAMAT_DOSSIER" VARCHAR2(150 BYTE) DEFAULT NULL, 
	"NIK_AM" NUMBER(6,0) DEFAULT NULL, 
	"NAMA_AM" VARCHAR2(100 BYTE) DEFAULT NULL, 
	"SEGMENT_6_LNAME" VARCHAR2(3 BYTE) DEFAULT NULL
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table PMS_SLI_DES_LAST_3_MONTH
--------------------------------------------------------

  CREATE TABLE "FASTEL"."PMS_SLI_DES_LAST_3_MONTH" 
   (	"TELP" VARCHAR2(15 BYTE) DEFAULT NULL, 
	"REV_N_1" NUMBER(15,0) DEFAULT NULL, 
	"REV_N_2" NUMBER(15,0) DEFAULT NULL, 
	"REV_N_3" NUMBER(15,0) DEFAULT NULL, 
	"RATA_RATA" NUMBER(15,0) DEFAULT NULL
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
REM INSERTING into FASTEL.DES_PROFILE_FASTEL_AM
SET DEFINE OFF;
Insert into FASTEL.DES_PROFILE_FASTEL_AM (NOTEL,NIP_NAS,STANDARD_NAME,ALAMAT_DOSSIER,NIK_AM,NAMA_AM,SEGMENT_6_LNAME) values ('02182608708','43211234','Asboen','Malaysia Barat','123432','Zig','DSS');
Insert into FASTEL.DES_PROFILE_FASTEL_AM (NOTEL,NIP_NAS,STANDARD_NAME,ALAMAT_DOSSIER,NIK_AM,NAMA_AM,SEGMENT_6_LNAME) values ('081383112888','76661667','Santoso','Sukolilo','986789','Jones','FSS');
REM INSERTING into FASTEL.PMS_SLI_DES_LAST_3_MONTH
SET DEFINE OFF;
Insert into FASTEL.PMS_SLI_DES_LAST_3_MONTH (TELP,REV_N_1,REV_N_2,REV_N_3,RATA_RATA) values ('02182608708','30','30','30','30');
Insert into FASTEL.PMS_SLI_DES_LAST_3_MONTH (TELP,REV_N_1,REV_N_2,REV_N_3,RATA_RATA) values ('081383112888','40','700','80','273');
--------------------------------------------------------
--  DDL for Index NOTEL
--------------------------------------------------------

  CREATE INDEX "FASTEL"."NOTEL" ON "FASTEL"."PMS_SLI_DES_LAST_3_MONTH" ("TELP") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table DES_PROFILE_FASTEL_AM
--------------------------------------------------------

  ALTER TABLE "FASTEL"."DES_PROFILE_FASTEL_AM" ADD PRIMARY KEY ("NOTEL")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "FASTEL"."DES_PROFILE_FASTEL_AM" MODIFY ("NOTEL" NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table PMS_SLI_DES_LAST_3_MONTH
--------------------------------------------------------

  ALTER TABLE "FASTEL"."PMS_SLI_DES_LAST_3_MONTH" ADD CONSTRAINT "REVENUE_IBFK_1" FOREIGN KEY ("TELP")
	  REFERENCES "FASTEL"."DES_PROFILE_FASTEL_AM" ("NOTEL") ENABLE;
