--------------------------------------------------------
--  File created - Wednesday-August-10-2016   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Sequence ACTIVITY_PARAMETER_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "FRAUD"."ACTIVITY_PARAMETER_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 70 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence CASE_PARAMETER_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "FRAUD"."CASE_PARAMETER_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 93 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence PROFILEUSER_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "FRAUD"."PROFILEUSER_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 65 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Table ACTIVITY
--------------------------------------------------------

  CREATE TABLE "FRAUD"."ACTIVITY" 
   (	"ID_CASE" VARCHAR2(100 BYTE) DEFAULT NULL, 
	"ACTIVITY_PARAMETER" VARCHAR2(200 BYTE) DEFAULT NULL, 
	"ACTIVITY_DATE" DATE DEFAULT NULL, 
	"DESCRIPTION" VARCHAR2(500 BYTE) DEFAULT NULL, 
	"INPUT_DATE" TIMESTAMP (6) DEFAULT NULL, 
	"FILENAME" VARCHAR2(100 BYTE) DEFAULT NULL, 
	"MIME" VARCHAR2(100 BYTE) DEFAULT NULL, 
	"ORIGINAL_FILENAME" VARCHAR2(100 BYTE) DEFAULT NULL
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table ACTIVITY_PARAMETER
--------------------------------------------------------

  CREATE TABLE "FRAUD"."ACTIVITY_PARAMETER" 
   (	"ID_PARAMETER" NUMBER(10,0), 
	"DESCRIPTION" VARCHAR2(200 BYTE) DEFAULT NULL, 
	"STATUS" CHAR(1 BYTE) DEFAULT NULL, 
	"AKRONIM" VARCHAR2(3 BYTE), 
	"AKTIF" CHAR(1 BYTE) DEFAULT 1
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table CASE_PARAMETER
--------------------------------------------------------

  CREATE TABLE "FRAUD"."CASE_PARAMETER" 
   (	"ID_PARAMETER" NUMBER(10,0), 
	"DESCRIPTION" VARCHAR2(200 BYTE) DEFAULT NULL, 
	"AKTIF" CHAR(1 BYTE) DEFAULT 1
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table KASUS
--------------------------------------------------------

  CREATE TABLE "FRAUD"."KASUS" 
   (	"ID_CASE" VARCHAR2(100 BYTE) DEFAULT NULL, 
	"CASE_PARAMETER" VARCHAR2(200 BYTE) DEFAULT NULL, 
	"CASE_TIME" DATE DEFAULT NULL, 
	"DESCRIPTION" VARCHAR2(500 BYTE) DEFAULT NULL, 
	"STATUS" VARCHAR2(20 BYTE) DEFAULT NULL, 
	"DESTINATION" VARCHAR2(100 BYTE) DEFAULT NULL, 
	"DESTINATION_NUMBER" VARCHAR2(15 BYTE) DEFAULT NULL, 
	"DURASI" NUMBER(10,0) DEFAULT NULL, 
	"NUMBER_OF_CALL" NUMBER(10,0) DEFAULT NULL, 
	"INPUT_DATE" TIMESTAMP (6) DEFAULT NULL, 
	"FILENAME" VARCHAR2(100 BYTE) DEFAULT NULL, 
	"MIME" VARCHAR2(100 BYTE) DEFAULT NULL, 
	"ORIGINAL_FILENAME" VARCHAR2(100 BYTE) DEFAULT NULL, 
	"LAST_ACTIVITY" VARCHAR2(3 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table PROFIL
--------------------------------------------------------

  CREATE TABLE "FRAUD"."PROFIL" 
   (	"ID_CASE" VARCHAR2(100 BYTE) DEFAULT NULL, 
	"TELEPHONE_NUMBER" VARCHAR2(15 BYTE) DEFAULT NULL, 
	"MAIN_NUMBER" VARCHAR2(15 BYTE) DEFAULT NULL, 
	"NIPNAS" NUMBER(8,0) DEFAULT NULL, 
	"CUSTOMER" VARCHAR2(150 BYTE) DEFAULT NULL, 
	"NIKAM" NUMBER(6,0) DEFAULT NULL, 
	"AM" VARCHAR2(100 BYTE) DEFAULT NULL, 
	"INSTALLATION" VARCHAR2(100 BYTE) DEFAULT NULL, 
	"SEGMEN" VARCHAR2(3 BYTE) DEFAULT NULL, 
	"REVENUE" NUMBER(15,0) DEFAULT NULL
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table PROFILEUSER
--------------------------------------------------------

  CREATE TABLE "FRAUD"."PROFILEUSER" 
   (	"ID" NUMBER(10,0), 
	"USERNAME" VARCHAR2(30 BYTE) DEFAULT NULL, 
	"PASSWD" VARCHAR2(1024 BYTE) DEFAULT NULL, 
	"PREVILEDGE" CHAR(1 BYTE) DEFAULT NULL, 
	"REMEMBER_TOKEN" VARCHAR2(100 BYTE) DEFAULT NULL
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
REM INSERTING into FRAUD.ACTIVITY
SET DEFINE OFF;
Insert into FRAUD.ACTIVITY (ID_CASE,ACTIVITY_PARAMETER,ACTIVITY_DATE,DESCRIPTION,INPUT_DATE,FILENAME,MIME,ORIGINAL_FILENAME) values ('3485b25f-6d25-43bb-8c57-502146cb227f','PERMINTAAN BLOKIR',to_date('13-08-2016','DD-MM-RRRR'),'Permintaan',to_timestamp('10-08-2016 00.00.00,000000000','DD-MM-RRRR HH24.MI.SSXFF'),'2.jpg',null,'C:/xampp/htdocs/fraud/file_activity/2.jpg');
Insert into FRAUD.ACTIVITY (ID_CASE,ACTIVITY_PARAMETER,ACTIVITY_DATE,DESCRIPTION,INPUT_DATE,FILENAME,MIME,ORIGINAL_FILENAME) values ('3485b25f-6d25-43bb-8c57-502146cb227f','TIKETING',to_date('13-08-2016','DD-MM-RRRR'),'Selesai',to_timestamp('10-08-2016 00.00.00,000000000','DD-MM-RRRR HH24.MI.SSXFF'),'6.png',null,'C:/xampp/htdocs/fraud/file_activity/6.png');
Insert into FRAUD.ACTIVITY (ID_CASE,ACTIVITY_PARAMETER,ACTIVITY_DATE,DESCRIPTION,INPUT_DATE,FILENAME,MIME,ORIGINAL_FILENAME) values ('148a8702-1466-4a94-b88f-afb3e3947b65','PERMINTAAN BLOKIR',to_date('22-08-2016','DD-MM-RRRR'),'Permintaan dilakukan besok',to_timestamp('09-08-2016 00.00.00,000000000','DD-MM-RRRR HH24.MI.SSXFF'),'33.jpg',null,'C:/xampp/htdocs/fraud/file_activity/33.jpg');
Insert into FRAUD.ACTIVITY (ID_CASE,ACTIVITY_PARAMETER,ACTIVITY_DATE,DESCRIPTION,INPUT_DATE,FILENAME,MIME,ORIGINAL_FILENAME) values ('3485b25f-6d25-43bb-8c57-502146cb227f','CARING PELANGGAN',to_date('12-08-2016','DD-MM-RRRR'),'Caring pelanggan',to_timestamp('10-08-2016 00.00.00,000000000','DD-MM-RRRR HH24.MI.SSXFF'),'71.png',null,'C:/xampp/htdocs/fraud/file_activity/71.png');
REM INSERTING into FRAUD.ACTIVITY_PARAMETER
SET DEFINE OFF;
Insert into FRAUD.ACTIVITY_PARAMETER (ID_PARAMETER,DESCRIPTION,STATUS,AKRONIM,AKTIF) values ('1','PERMINTAAN BLOKIR','0','PBL','1');
Insert into FRAUD.ACTIVITY_PARAMETER (ID_PARAMETER,DESCRIPTION,STATUS,AKRONIM,AKTIF) values ('2','BLOKIR SLI','0','BLS','1');
Insert into FRAUD.ACTIVITY_PARAMETER (ID_PARAMETER,DESCRIPTION,STATUS,AKRONIM,AKTIF) values ('3','CARING PELANGGAN','0','CPL','1');
Insert into FRAUD.ACTIVITY_PARAMETER (ID_PARAMETER,DESCRIPTION,STATUS,AKRONIM,AKTIF) values ('4','RESPON PELANGGAN','0','RPL','1');
Insert into FRAUD.ACTIVITY_PARAMETER (ID_PARAMETER,DESCRIPTION,STATUS,AKRONIM,AKTIF) values ('5','SURAT PELANGGAN','0','SPL','1');
Insert into FRAUD.ACTIVITY_PARAMETER (ID_PARAMETER,DESCRIPTION,STATUS,AKRONIM,AKTIF) values ('6','TICKETING','1','TCT','1');
Insert into FRAUD.ACTIVITY_PARAMETER (ID_PARAMETER,DESCRIPTION,STATUS,AKRONIM,AKTIF) values ('7','BUKA BLOKIR/TAGIH','1','BBT','1');
Insert into FRAUD.ACTIVITY_PARAMETER (ID_PARAMETER,DESCRIPTION,STATUS,AKRONIM,AKTIF) values ('9','BLOKIR PERMANEN','1','BP','1');
Insert into FRAUD.ACTIVITY_PARAMETER (ID_PARAMETER,DESCRIPTION,STATUS,AKRONIM,AKTIF) values ('50','BLOKIR LAMA','0','BKL','0');
REM INSERTING into FRAUD.CASE_PARAMETER
SET DEFINE OFF;
Insert into FRAUD.CASE_PARAMETER (ID_PARAMETER,DESCRIPTION,AKTIF) values ('1','ONE TO MANY','1');
Insert into FRAUD.CASE_PARAMETER (ID_PARAMETER,DESCRIPTION,AKTIF) values ('2','MANY TO ONE','1');
Insert into FRAUD.CASE_PARAMETER (ID_PARAMETER,DESCRIPTION,AKTIF) values ('74','ONE TO ONE','1');
Insert into FRAUD.CASE_PARAMETER (ID_PARAMETER,DESCRIPTION,AKTIF) values ('54','MANY TO MANY','1');
Insert into FRAUD.CASE_PARAMETER (ID_PARAMETER,DESCRIPTION,AKTIF) values ('75','ONE TO THREE','0');
REM INSERTING into FRAUD.KASUS
SET DEFINE OFF;
Insert into FRAUD.KASUS (ID_CASE,CASE_PARAMETER,CASE_TIME,DESCRIPTION,STATUS,DESTINATION,DESTINATION_NUMBER,DURASI,NUMBER_OF_CALL,INPUT_DATE,FILENAME,MIME,ORIGINAL_FILENAME,LAST_ACTIVITY) values ('d05c0dc9-77fb-47d1-84cb-64e9bf6bbe2d','ONE TO MANY',to_date('20-07-2016','DD-MM-RRRR'),'Kasus kedua','0','Albania Barat','08975557763','60000','600',to_timestamp('10-08-2016 00.00.00,000000000','DD-MM-RRRR HH24.MI.SSXFF'),'2.jpg',null,'C:/xampp/htdocs/fraud/case_activity/2.jpg',null);
Insert into FRAUD.KASUS (ID_CASE,CASE_PARAMETER,CASE_TIME,DESCRIPTION,STATUS,DESTINATION,DESTINATION_NUMBER,DURASI,NUMBER_OF_CALL,INPUT_DATE,FILENAME,MIME,ORIGINAL_FILENAME,LAST_ACTIVITY) values ('3485b25f-6d25-43bb-8c57-502146cb227f','MANY TO MANY',to_date('10-08-2016','DD-MM-RRRR'),'Kasus telepon ke malaysia','1','Malaysia','0314666777','7200','30',to_timestamp('10-08-2016 00.00.00,000000000','DD-MM-RRRR HH24.MI.SSXFF'),'21.jpg',null,'C:/xampp/htdocs/fraud/case_activity/21.jpg','TKT');
Insert into FRAUD.KASUS (ID_CASE,CASE_PARAMETER,CASE_TIME,DESCRIPTION,STATUS,DESTINATION,DESTINATION_NUMBER,DURASI,NUMBER_OF_CALL,INPUT_DATE,FILENAME,MIME,ORIGINAL_FILENAME,LAST_ACTIVITY) values ('148a8702-1466-4a94-b88f-afb3e3947b65','MANY TO MANY',to_date('20-06-2016','DD-MM-RRRR'),'Kasus pertama','0','Indonesia','0314666789','3600','30',to_timestamp('09-08-2016 00.00.00,000000000','DD-MM-RRRR HH24.MI.SSXFF'),'42.jpg',null,'C:/xampp/htdocs/fraud/case_activity/42.jpg','PBL');
REM INSERTING into FRAUD.PROFIL
SET DEFINE OFF;
Insert into FRAUD.PROFIL (ID_CASE,TELEPHONE_NUMBER,MAIN_NUMBER,NIPNAS,CUSTOMER,NIKAM,AM,INSTALLATION,SEGMEN,REVENUE) values ('148a8702-1466-4a94-b88f-afb3e3947b65','081383112806','081383112888','76661667','Santoso','986789','Jones','Sukolilo','FSS','273');
Insert into FRAUD.PROFIL (ID_CASE,TELEPHONE_NUMBER,MAIN_NUMBER,NIPNAS,CUSTOMER,NIKAM,AM,INSTALLATION,SEGMEN,REVENUE) values ('3485b25f-6d25-43bb-8c57-502146cb227f','08967776554','03135766599','55555555','Bank BNI','600000','Afif Ishamsyah','Thamrin','BMS','450000');
Insert into FRAUD.PROFIL (ID_CASE,TELEPHONE_NUMBER,MAIN_NUMBER,NIPNAS,CUSTOMER,NIKAM,AM,INSTALLATION,SEGMEN,REVENUE) values ('d05c0dc9-77fb-47d1-84cb-64e9bf6bbe2d','09188827777','02182608708','43211234','Asboen','123432','Zig','Malaysia Barat','DSS','30');
REM INSERTING into FRAUD.PROFILEUSER
SET DEFINE OFF;
Insert into FRAUD.PROFILEUSER (ID,USERNAME,PASSWD,PREVILEDGE,REMEMBER_TOKEN) values ('26','ciampas','653cc1eb3a49f2a9d4dd1abdd424c97e','0',null);
Insert into FRAUD.PROFILEUSER (ID,USERNAME,PASSWD,PREVILEDGE,REMEMBER_TOKEN) values ('45','laraveldewa','176457523d5ef9d5425ef5837f5b895a','1',null);
--------------------------------------------------------
--  DDL for Index ID_CASES
--------------------------------------------------------

  CREATE INDEX "FRAUD"."ID_CASES" ON "FRAUD"."ACTIVITY" ("ID_CASE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index CASE_PARAMETER
--------------------------------------------------------

  CREATE INDEX "FRAUD"."CASE_PARAMETER" ON "FRAUD"."KASUS" ("CASE_PARAMETER") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index ACTIVITY_NUMBER
--------------------------------------------------------

  CREATE INDEX "FRAUD"."ACTIVITY_NUMBER" ON "FRAUD"."ACTIVITY" ("ACTIVITY_PARAMETER") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index ID_CASE
--------------------------------------------------------

  CREATE INDEX "FRAUD"."ID_CASE" ON "FRAUD"."PROFIL" ("ID_CASE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table CASE_PARAMETER
--------------------------------------------------------

  ALTER TABLE "FRAUD"."CASE_PARAMETER" ADD PRIMARY KEY ("ID_PARAMETER")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "FRAUD"."CASE_PARAMETER" MODIFY ("ID_PARAMETER" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table PROFILEUSER
--------------------------------------------------------

  ALTER TABLE "FRAUD"."PROFILEUSER" ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "FRAUD"."PROFILEUSER" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table KASUS
--------------------------------------------------------

  ALTER TABLE "FRAUD"."KASUS" ADD PRIMARY KEY ("ID_CASE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "FRAUD"."KASUS" MODIFY ("ID_CASE" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table ACTIVITY_PARAMETER
--------------------------------------------------------

  ALTER TABLE "FRAUD"."ACTIVITY_PARAMETER" ADD PRIMARY KEY ("ID_PARAMETER")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "FRAUD"."ACTIVITY_PARAMETER" MODIFY ("ID_PARAMETER" NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table ACTIVITY
--------------------------------------------------------

  ALTER TABLE "FRAUD"."ACTIVITY" ADD CONSTRAINT "ACTIVITY_IBFK_6" FOREIGN KEY ("ID_CASE")
	  REFERENCES "FRAUD"."KASUS" ("ID_CASE") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table PROFIL
--------------------------------------------------------

  ALTER TABLE "FRAUD"."PROFIL" ADD CONSTRAINT "PROFILE_IBFK_1" FOREIGN KEY ("ID_CASE")
	  REFERENCES "FRAUD"."KASUS" ("ID_CASE") ENABLE;
--------------------------------------------------------
--  DDL for Trigger ACTIVITY_PARAMETER_SEQ_TR
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "FRAUD"."ACTIVITY_PARAMETER_SEQ_TR" 
 BEFORE INSERT ON activity_parameter FOR EACH ROW
  WHEN (NEW.id_parameter IS NULL) BEGIN
 SELECT activity_parameter_seq.NEXTVAL INTO :NEW.id_parameter FROM DUAL;
END;
/
ALTER TRIGGER "FRAUD"."ACTIVITY_PARAMETER_SEQ_TR" ENABLE;
--------------------------------------------------------
--  DDL for Trigger CASE_PARAMETER_SEQ_TR
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "FRAUD"."CASE_PARAMETER_SEQ_TR" 
 BEFORE INSERT ON case_parameter FOR EACH ROW
  WHEN (NEW.id_parameter IS NULL) BEGIN
 SELECT case_parameter_seq.NEXTVAL INTO :NEW.id_parameter FROM DUAL;
END;
/
ALTER TRIGGER "FRAUD"."CASE_PARAMETER_SEQ_TR" ENABLE;
--------------------------------------------------------
--  DDL for Trigger PROFILEUSER_SEQ_TR
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "FRAUD"."PROFILEUSER_SEQ_TR" 
 BEFORE INSERT ON profileuser FOR EACH ROW
  WHEN (NEW.id IS NULL) BEGIN
 SELECT profileuser_seq.NEXTVAL INTO :NEW.id FROM DUAL;
END;
/
ALTER TRIGGER "FRAUD"."PROFILEUSER_SEQ_TR" ENABLE;
