--------------------------------------------------------
--  File created - Wednesday-August-10-2016   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table PROFIL
--------------------------------------------------------

  CREATE TABLE "FASTEL"."PROFIL" 
   (	"NOTEL" VARCHAR2(15 BYTE), 
	"NIPNAS" NUMBER(8,0) DEFAULT NULL, 
	"NAMACC" VARCHAR2(150 BYTE) DEFAULT NULL, 
	"ALAMAT" VARCHAR2(150 BYTE) DEFAULT NULL, 
	"NIKAM" NUMBER(6,0) DEFAULT NULL, 
	"NAMAAM" VARCHAR2(100 BYTE) DEFAULT NULL, 
	"SEGMEN" VARCHAR2(3 BYTE) DEFAULT NULL
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table REVENUE
--------------------------------------------------------

  CREATE TABLE "FASTEL"."REVENUE" 
   (	"NOTEL" VARCHAR2(15 BYTE) DEFAULT NULL, 
	"REV1" NUMBER(15,0) DEFAULT NULL, 
	"REV2" NUMBER(15,0) DEFAULT NULL, 
	"REV3" NUMBER(15,0) DEFAULT NULL, 
	"AVERAGE" NUMBER(15,0) DEFAULT NULL
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
REM INSERTING into FASTEL.PROFIL
SET DEFINE OFF;
Insert into FASTEL.PROFIL (NOTEL,NIPNAS,NAMACC,ALAMAT,NIKAM,NAMAAM,SEGMEN) values ('02182608708','43211234','Asboen','Malaysia Barat','123432','Zig','DSS');
Insert into FASTEL.PROFIL (NOTEL,NIPNAS,NAMACC,ALAMAT,NIKAM,NAMAAM,SEGMEN) values ('081383112888','76661667','Santoso','Sukolilo','986789','Jones','FSS');
REM INSERTING into FASTEL.REVENUE
SET DEFINE OFF;
Insert into FASTEL.REVENUE (NOTEL,REV1,REV2,REV3,AVERAGE) values ('02182608708','30','30','30','30');
Insert into FASTEL.REVENUE (NOTEL,REV1,REV2,REV3,AVERAGE) values ('081383112888','40','700','80','273');
--------------------------------------------------------
--  DDL for Index NOTEL
--------------------------------------------------------

  CREATE INDEX "FASTEL"."NOTEL" ON "FASTEL"."REVENUE" ("NOTEL") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table PROFIL
--------------------------------------------------------

  ALTER TABLE "FASTEL"."PROFIL" ADD PRIMARY KEY ("NOTEL")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "FASTEL"."PROFIL" MODIFY ("NOTEL" NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table REVENUE
--------------------------------------------------------

  ALTER TABLE "FASTEL"."REVENUE" ADD CONSTRAINT "REVENUE_IBFK_1" FOREIGN KEY ("NOTEL")
	  REFERENCES "FASTEL"."PROFIL" ("NOTEL") ENABLE;
